# create your drupal and postgres config here, based off the last assignment
version: '3.5'

services:

  example_db:
    image: postgres:9.6.9-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dtmqEqrKc67ykGc
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  example_web:
    image: awsbeanstalkwithdatabase
    build: .
    ports:
      - 8080:8080
    depends_on:
      - example_db