---
name: 'Java CI'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Setup java 11'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache ~/.m2/repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-repository-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-repository-
      - name: 'Compile and run tests with maven'
        run: 'mvn -B verify'
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ROOT.war
          path: target/ROOT.war
